// <auto-generated />
namespace Softtek.Academy2018.Demo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class refactoring_to_user_projects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoring_to_user_projects));
        
        string IMigrationMetadata.Id
        {
            get { return "201802170337267_refactoring_to_user_projects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
