USE [master]
GO

/****** Object:  Database [ToDoList_<IAGT>]    Script Date: 1/30/2018 8:29:13 PM ******/
CREATE DATABASE [ToDoList_<IAGT>]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ToDoList__IAGT_', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ToDoList__IAGT_.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ToDoList__IAGT__log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ToDoList__IAGT__log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ToDoList_<IAGT>] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ToDoList_<IAGT>].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ToDoList_<IAGT>] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET ARITHABORT OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET  MULTI_USER 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ToDoList_<IAGT>] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ToDoList_<IAGT>] SET QUERY_STORE = OFF
GO

USE [ToDoList_<IAGT>]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ToDoList_<IAGT>] SET  READ_WRITE 
GO

