// <auto-generated />
namespace Softtek.Academy2018.ToDoListApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TagSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TagSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201803022314201_TagSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
