//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/Softtek.Academy2018.Demo.WCF.Messages")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectRequest))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllProjectsRequest", Namespace="http://schemas.datacontract.org/2004/07/Softtek.Academy2018.Demo.WCF.Messages")]
    [System.SerializableAttribute()]
    public partial class GetAllProjectsRequest : Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateProjectRequest", Namespace="http://schemas.datacontract.org/2004/07/Softtek.Academy2018.Demo.WCF.Messages")]
    [System.SerializableAttribute()]
    public partial class CreateProjectRequest : Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnologyStackField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnologyStack {
            get {
                return this.TechnologyStackField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnologyStackField, value) != true)) {
                    this.TechnologyStackField = value;
                    this.RaisePropertyChanged("TechnologyStack");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/Softtek.Academy2018.Demo.WCF.Messages")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllProjectsResponse", Namespace="http://schemas.datacontract.org/2004/07/Softtek.Academy2018.Demo.WCF.Messages")]
    [System.SerializableAttribute()]
    public partial class GetAllProjectsResponse : Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.ProjectDTO[] ProjectListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.ProjectDTO[] ProjectList {
            get {
                return this.ProjectListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectListField, value) != true)) {
                    this.ProjectListField = value;
                    this.RaisePropertyChanged("ProjectList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateProjectResponse", Namespace="http://schemas.datacontract.org/2004/07/Softtek.Academy2018.Demo.WCF.Messages")]
    [System.SerializableAttribute()]
    public partial class CreateProjectResponse : Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectDTO", Namespace="http://schemas.datacontract.org/2004/07/Softtek.Academy2018.Demo.WCF.Messages")]
    [System.SerializableAttribute()]
    public partial class ProjectDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnologyStackField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnologyStack {
            get {
                return this.TechnologyStackField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnologyStackField, value) != true)) {
                    this.TechnologyStackField = value;
                    this.RaisePropertyChanged("TechnologyStack");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProjectManagementService_Ref.IProjectManagementService")]
    public interface IProjectManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectManagementService/CreateProject", ReplyAction="http://tempuri.org/IProjectManagementService/CreateProjectResponse")]
        Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectResponse CreateProject(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectManagementService/CreateProject", ReplyAction="http://tempuri.org/IProjectManagementService/CreateProjectResponse")]
        System.Threading.Tasks.Task<Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectResponse> CreateProjectAsync(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectManagementService/GetAllProjects", ReplyAction="http://tempuri.org/IProjectManagementService/GetAllProjectsResponse")]
        Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsResponse GetAllProjects(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectManagementService/GetAllProjects", ReplyAction="http://tempuri.org/IProjectManagementService/GetAllProjectsResponse")]
        System.Threading.Tasks.Task<Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsResponse> GetAllProjectsAsync(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectManagementServiceChannel : Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.IProjectManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectManagementServiceClient : System.ServiceModel.ClientBase<Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.IProjectManagementService>, Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.IProjectManagementService {
        
        public ProjectManagementServiceClient() {
        }
        
        public ProjectManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectResponse CreateProject(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectRequest request) {
            return base.Channel.CreateProject(request);
        }
        
        public System.Threading.Tasks.Task<Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectResponse> CreateProjectAsync(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.CreateProjectRequest request) {
            return base.Channel.CreateProjectAsync(request);
        }
        
        public Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsResponse GetAllProjects(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsRequest request) {
            return base.Channel.GetAllProjects(request);
        }
        
        public System.Threading.Tasks.Task<Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsResponse> GetAllProjectsAsync(Softtek.Academy2018.Demo.Console.ProjectManagementService_Ref.GetAllProjectsRequest request) {
            return base.Channel.GetAllProjectsAsync(request);
        }
    }
}
