// <auto-generated />
namespace Softtek.Academy2018.SurveyApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class many_to_many_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(many_to_many_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "201802210854225_many_to_many_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
