// <auto-generated />
namespace Softtek.Academy2018.SurveyApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_context_add_option_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_context_add_option_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201802210852330_update_context_add_option_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
